# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/**/*"
    - "!assets/{img,js,scss}/**/*"
    - "node_modules/@fortawesome/fontawesome-free/**/*"
    - "!node_modules/@fortawesome/fontawesome-free/{css,less,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
    - "node_modules/@fortawesome/fontawesome-free/scss"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "assets/js/app.js"
  # Paths to Sass entry points to be generated into css files
  sass_entries:
    - "assets/scss/app.scss"
