# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "static/dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/**/*"
    - "!assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "assets/js/app.js"
    - "assets/js/fontawesome/fontawesome-all.min.js"
    - "node_modules/foundation-sites/dist/js/foundation.min.js"
    - "node_modules/jquery/dist/jquery.min.js"
    - "node_modules/what-input/dist/what-input.min.js"
