* Fetch the source

** BETA

git checkout develop
git pull

** PROD

git checkout master
git pull

* Check config

Check that the config (especially db uri) is correct. In any case,
running the beta /shouldn't/ have permissions to alter the prod db.

cat pmp6.sexp

* Get env

rm -fr _opam
opam update

# These instructions may not be up-to-date: OCaml version needs to
# match the lockfile
opam switch create . ocaml-base-compiler.5.2.1 --locked --deps-only
eval $(opam env)

# Some locked packages may be not found if they have been pruned from
# latest opam repository. If that happens, either recreate an update
# lockfile if convenient, otherwise (eg. to redeploy an old master
# build) use the archive repository:
opam switch create . ocaml-base-compiler.5.2.1 --locked --repos default,archive=https://github.com/ocaml/opam-repository-archive.git

# Compilation might fail because of disk space... To restart:
opam clean
opam pin add . --locked

# Post-build cache clean may help for future deployments
opam clean

rm -fr node_modules
yarn

* Compile backend

Note: opt compiles, but running doesn't seem to work right now due to an async issue.

make distclean
make byte # Don't use -j as this will oom

* Compile frontend

yarn build

* Deploy database

** BETA

sqlite3 pmp6_beta.db ".backup backup.db"
sqitch deploy --verify db:sqlite:pmp6_beta.db

** PROD

sqlite3 /var/local/pmp6/pmp6.db ".backup backup.db"
sudo sqitch deploy --verify db:sqlite:/var/local/pmp6/pmp6.db

* install

** BETA

No need to install

** PROD

sudo make install-unit # If needed
sudo systemctl daemon-reload # If the unit was reinstalled
sudo make install.byte

* Check and update nginx conf

** BETA

diff nginx_conf/beta.pmp6.fr.conf /etc/nginx/conf.d/beta.pmp6.fr.conf
sudo systemctl reload nginx.service

** PROD

diff nginx_conf/pmp6.fr.conf /etc/nginx/conf.d/pmp6.fr.conf
sudo systemctl reload nginx.service

* Run

** BETA

./test

** PROD

sudo systemctl stop pmp6-site
sudo systemctl enable pmp6-site
systemctl status pmp6-site
sudo systemctl start pmp6-site # If needed
